# Generated by Django 5.0.1 on 2024-02-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="end_time",
            new_name="end_work",
        ),
    ]
