version: "3.10"
services:
  database_selim:
    container_name: db_selim
    image: postgres:latest
    volumes:
      - .db_selim/postgres/:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "12345"

  web:
    container_name: selim_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/backend_selim
    env_file:
      - .env
    depends_on:
      - database_selim
